### ISSUE TITLE
rdx is popped two times (instead of rbx)

### ISSUE THREAD

**Issue by vfsfitvnm** [DavidBuchanan314/dlinject#6]
https://github.com/DavidBuchanan314/dlinject/blob/b9b9a8c8fa5130d408e523c53868bef5f4643a59/dlinject.py#L276

I guess this should have been `pop rbx`.

**Comment by DavidBuchanan314** [comment]
Good spot, I'm surprised this bug wasn't causing more serious issues already. Just fixed.
